# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

sudo: false
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
virtualenv:
  system_site_packages: false
env:
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="3.3" COVERAGE="false"
    - DISTRIB="conda" PYTHON_VERSION="3.4" COVERAGE="false"
    - DISTRIB="conda" PYTHON_VERSION="3.6" COVERAGE="true"
    - DISTRIB="ubuntu" PYTHON_VERSION="3.6" COVERAGE="true"




addons:
  apt:
    packages:
      - git
      - python-pip
install:
  - source tests/travis_install.sh
  - pip install -r requirements.txt
  - pip install -U setuptools
  - pip install pathlib

before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
script:
  - python setup.py test
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
cache:
  - apt
